"""X1 chain provider integrations for CMIS."""

from .canonical_pool_vault_coupling import prove_canonical_pool_vault_coupling
from .health import (
    HEALTH_SOURCE,
    HEALTH_URL,
    X1HealthAPIError,
    X1HealthProvider,
    fetch_health,
    parse_health,
)
from .market import (
    CHAIN,
    DEFAULT_REFRESH_SECONDS,
    MARKET_SOURCE,
    MAX_CATALOG_OFFSET,
    PAGE_SIZE,
    POOLS_URL,
    X1Provider,
    XDEXCatalog,
    fetch_all_pools,
)
from .network import (
    NETWORK_SOURCE,
    X1NetworkAPIError,
    X1NetworkProvider,
    fetch_network_snapshot,
    parse_network_snapshot,
)
from .network_history import (
    CLUSTER_HISTORY_URL,
    DEFAULT_GROUP_BY as HISTORY_DEFAULT_GROUP_BY,
    DEFAULT_ORDER as HISTORY_DEFAULT_ORDER,
    DEFAULT_PROPERTIES as HISTORY_DEFAULT_PROPERTIES,
    NETWORK_HISTORY_SOURCE,
    X1NetworkHistoryAPIError,
    X1NetworkHistoryProvider,
    fetch_cluster_history,
    parse_cluster_history,
)
from .ninja_history import (
    TRADE_HISTORY_PATH as X1_NINJA_TRADE_HISTORY_PATH,
    X1_NINJA_API_BASE_URL,
    X1_NINJA_SOURCE,
    X1NinjaAPIError,
    fetch_pool_trades_raw as fetch_x1_ninja_pool_trades_raw,
)
from .rpc import (
    DEFAULT_X1_RPC_URL,
    RPC_SOURCE,
    X1RPCError,
    X1RPCProvider,
    get_mint_info,
    get_token_account_info,
    get_token_supply,
    parse_mint_account_result,
    parse_token_account_result,
    parse_token_supply_result,
    rpc_request,
)
from .rpc_supply import (
    RPC_NETWORK_SUPPLY_SOURCE,
    X1RPCSupplyError,
    X1RPCSupplyProvider,
    get_network_supply_rpc,
    parse_network_supply_result,
)
from .supply import (
    ASSET as SUPPLY_ASSET,
    DEFAULT_NETWORK as SUPPLY_DEFAULT_NETWORK,
    SUPPLY_API_BASE_URL,
    SUPPLY_SOURCE,
    X1SupplyAPIError,
    X1SupplyProvider,
    fetch_supply,
    get_circulating_supply,
    get_total_supply as get_x1_network_total_supply,
    parse_supply_text,
)
from .xdex import (
    PRICE_HISTORY_URL as XDEX_PRICE_HISTORY_URL,
    SWAP_QUOTE_URL as XDEX_SWAP_QUOTE_URL,
    TOKEN_PRICE_URL as XDEX_TOKEN_PRICE_URL,
    XDEX_API_BASE_URL,
    XDEX_NETWORK_X1_MAINNET,
    XDEX_SOURCE,
    XDEXAPIError,
    XDEXReadOnlyProvider,
    fetch_price_history as fetch_xdex_price_history,
    fetch_swap_quote as fetch_xdex_swap_quote,
    fetch_token_price as fetch_xdex_token_price,
)

__all__ = [
    "CHAIN",
    "CLUSTER_HISTORY_URL",
    "DEFAULT_REFRESH_SECONDS",
    "DEFAULT_X1_RPC_URL",
    "HEALTH_SOURCE",
    "HEALTH_URL",
    "HISTORY_DEFAULT_GROUP_BY",
    "HISTORY_DEFAULT_ORDER",
    "HISTORY_DEFAULT_PROPERTIES",
    "MARKET_SOURCE",
    "MAX_CATALOG_OFFSET",
    "NETWORK_HISTORY_SOURCE",
    "NETWORK_SOURCE",
    "PAGE_SIZE",
    "POOLS_URL",
    "RPC_NETWORK_SUPPLY_SOURCE",
    "RPC_SOURCE",
    "SUPPLY_API_BASE_URL",
    "SUPPLY_ASSET",
    "SUPPLY_DEFAULT_NETWORK",
    "SUPPLY_SOURCE",
    "X1HealthAPIError",
    "X1HealthProvider",
    "X1NetworkAPIError",
    "X1NetworkHistoryAPIError",
    "X1NetworkHistoryProvider",
    "X1NetworkProvider",
    "X1NinjaAPIError",
    "X1Provider",
    "X1RPCError",
    "X1RPCProvider",
    "X1RPCSupplyError",
    "X1RPCSupplyProvider",
    "X1SupplyAPIError",
    "X1SupplyProvider",
    "X1_NINJA_API_BASE_URL",
    "X1_NINJA_SOURCE",
    "X1_NINJA_TRADE_HISTORY_PATH",
    "XDEXCatalog",
    "XDEXAPIError",
    "XDEXReadOnlyProvider",
    "XDEX_API_BASE_URL",
    "XDEX_NETWORK_X1_MAINNET",
    "XDEX_PRICE_HISTORY_URL",
    "XDEX_SOURCE",
    "XDEX_SWAP_QUOTE_URL",
    "XDEX_TOKEN_PRICE_URL",
    "fetch_all_pools",
    "fetch_cluster_history",
    "fetch_health",
    "fetch_network_snapshot",
    "fetch_supply",
    "fetch_x1_ninja_pool_trades_raw",
    "fetch_xdex_price_history",
    "fetch_xdex_swap_quote",
    "fetch_xdex_token_price",
    "get_circulating_supply",
    "get_mint_info",
    "get_network_supply_rpc",
    "get_token_account_info",
    "get_token_supply",
    "get_x1_network_total_supply",
    "parse_cluster_history",
    "parse_health",
    "parse_mint_account_result",
    "parse_network_snapshot",
    "parse_network_supply_result",
    "parse_supply_text",
    "parse_token_account_result",
    "parse_token_supply_result",
    "prove_canonical_pool_vault_coupling",
    "rpc_request",
]
